- go.mod
Related to https://github.com/GoogleCloudPlatform/terraform-validator/issues/158. I am still able to run `make test` successfully after this upgrade.
> Bumped go version to 1.14

- conversion/tfplan_to_cai.go
- conversion/tfplan_to_cai_test.go
A context.Context object should not be stored inside a struct unless needed for backward compatibility and instead is to be explicitly passed as the first argument all along the function call chains.
> Update TFPlanToCAI function signature to follow the guideline at https://go.dev/blog/context-and-structs

- cai2hcl/compute_instance.go
- testdata/full_compute_instance.json
The zone now is like "zone": "projects/project-name/zones/us-east1-b"
It should be like "zone": "us-east1-b" instead
b/273835909
> Correct instance zone

- .ci/cloudbuild-tests-go-licenses.yaml
- .ci/cloudbuild-tests-unit.yaml
- Dockerfile
- go.mod
Reverts GoogleCloudPlatform/terraform-google-conversion#820.  It looks like the Magic Modules downstream build pipeline is not compatible with go 1.19 at the moment - see https://pantheon.corp.google.com/cloud-build/builds/caef7cf1-bdda-4079-9d28-5e9c6d1957fb;step=10?jsmode=O&mods=logs_tg_staging&project=graphite-docker-images
> Revert "Update go version to 1.19"

- cai2hcl/common.go
- cai2hcl/compute_forwarding_rule.go
- cai2hcl/compute_forwarding_rule_test.go
- cai2hcl/compute_instance_test.go
- cai2hcl/test_helper.go
- testdata/full_compute_forwarding_rule.json
- testdata/full_compute_forwarding_rule.tf
This is a first step to support conversion from CAI to HCL for GCP Compute Load Balancing resources.
> Add cai2hcl converter for ComputeForwardingRule creation

- Makefile
The library has a BSD2 license, but the license library does not report a high confidence for it to be considered a BSD2.
> fix(license): skip checking vcr library

- cai2hcl/common.go
- tfplan2cai/tfdata/fake_resource_data_test.go
Import provider package from `github.com/hashicorp/terraform-provider-google-beta/google-beta/provider` instead of `github.com/hashicorp/terraform-provider-google-beta/google-beta`, as the latter one will be cleaned up.
> Import provider package

- tfplan2cai/converters/google/resources/getconfig_test.go
This allows tests to pass locally when `GOOGLE_CREDENTIALS` or `GOOGLE_CLOUD_KEYFILE_JSON` are set.
> Unset other credentials variables before constructing config

- go.mod
This PR accompanies this PR (https://github.com/GoogleCloudPlatform/magic-modules/pull/9506) to update the google and google-beta providers to Go 1.20
> Update to Go 1.20

- go.mod
Reverts GoogleCloudPlatform/terraform-google-conversion#1728
> Revert "Update to Go 1.20"

- go.mod
This PR accompanies this PR (https://github.com/GoogleCloudPlatform/magic-modules/pull/9506) to update the google and google-beta providers to Go 1.20
> chore: update to Go 1.20

- config-tf-dev-override.sh
Failures appeared in our CI pipeline since the VM doesn't actually state a GOPATH location.
https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/7403766487/job/20144262649
Instead of fixing this in all the consumers I'm just going to fix it here.
> reference GOPATH directly

- docs/contributing/add_new_resource.md
`make tgc` takes the root directory now, since we also generate cai2hcl
> corrected make tgc docs

- Makefile
This should fix unit tests by making them not rely on the presence of that env var
> Switched from PWD env var to pwd command

- go.mod
A follow up to the PRs for upgrading to go 1.23 in magic-modules
> `chore`: update to go 1.23

- .ci/cloudbuild-tests-go-licenses.yaml
The reason for `test-go-licenses` failing before is that it uses go:1.18, which doesn't match with the current go version 1.23 of TGC.
> fix: fix test-go-licenses command

- v6/cmd/root.go
- v6/cmd/tfplan2cai/convert.go
- v6/cmd/tfplan2cai/convert_test.go
- v6/cmd/tfplan2cai/tfplan2cai.go
- v6/pkg/caiasset/asset.go
Copy the tfplan2cai command from v5 to v6 and then reorganize the folder structure
The supported command
tgc tfplan2cai convert ./example/terraform.tfplan --project my-project --ancestry organization/my-org/folder/my-folder
> feat: add V6 tfplan2cai cmd

- v6/cmd/cai2hcl/cai2hcl.go
- v6/cmd/cai2hcl/convert.go
- v6/cmd/cai2hcl/convert_test.go
- v6/cmd/root.go
This PR adds cai2hcl command to v6.
The supported command:
tgc cai2hcl convert ./example/example.json
> feat: add cai2hcl command to v6

- tfplan2cai/tfdata/fake_resource_data_test.go
The new fields added in https://github.com/GoogleCloudPlatform/magic-modules/pull/12672 caused the test TestFakeResourceData_getOkTypeObject fail. This PR is going to fix this test.
> test: fix TestFakeResourceData_getOkTypeObject

- cmd/tgc/cai2hcl/convert.go
- go.mod
- go.sum
In the roundtrip testing, cai2hcl -> tfplan2cai -> cai2hcl -> tfplan2cai, the output of tfplan2cai will be the input of cai2hcl.
Currently, tfplan2cai returns `[]caiasset.Asset`, but the input of cai2hcl is `[]*caiasset.Asset`. To make the roundtrip testing work smoothly, change the input of cai2hcl to `[]caiasset.Asset`.
This PR needs to be merged together with PR https://github.com/GoogleCloudPlatform/magic-modules/pull/13719 to make the tests pass.
> feat: (tgc-revial) modify parameter type for cai2hcl

- Makefile
Increase the test timeout to 30m for now to run tests with the new testing framework
> chore: increase the test timeout to 30m

- caiasset/asset.go
Certificatemanager resources require a location field for implementation of cai2hcl mapping. Discussed with @zli82016
> Add location field to CAI Asset Resource Type
